# Generated by Django 4.1.3 on 2022-11-09 06:44

from django.db import migrations, models
import meet.models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_alter_channelmember_options_remove_channel_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='invite_code',
            field=models.CharField(default=meet.models.random_code, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='channelmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=50),
        ),
    ]
